version: '3.9'

services:
  app:
    image: sellay2025/sellay:latest
    restart: always
    ports:
      - 3000:3000
    working_dir: /app
    container_name: app
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ${PWD}/../volumes:/data/db
