name: CI/CD Workflow

on:
  push:
    branches: [ "main" , "features/cicd" ]
  pull_request:
    branches: [ "main" , "features/cicd"]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Docker Login
      env:
        DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        NODE_ENV: development
      run: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sellay2025/sellay:latest
    - name: Push to docker registry
      run: docker push sellay2025/sellay:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Pull docker container
        run: sudo docker pull sellay2025/sellay:latest
      - name: Delete old docker container
        run: sudo docker compose -f docker-compose.prod.yml down --rmi all --remove-orphans -v || true
      - name: Write secret to file
        run: echo "${{ secrets.ALL }}" > .env
      - name: Run Docker container
        run: sudo docker compose -f docker-compose.prod.yml up -e NODE_ENV=development -d